### ISSUE TITLE
JVM IR transformation with kotlin 1.7.20-Beta bug in objects

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx-atomicfu#241]
Looks like starting from kotlin 1.7.20-Beta (kotlinx.atomicfu version is 0.18.3) `kotlinx.atomicfu.enableIrTransformation=true` flag also affects JVM target. And there is a bug when trying to instantiate an object with atomic field inside it:
```
java.lang.IllegalArgumentException 
   at sun.misc.Unsafe.objectFieldOffset(Native Method) 
   at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:426) 
   at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:88) 
   at io.rsocket.kotlin.transport.tests.PortProvider.<clinit>(PortProvider.kt:27)
```

Reproducer branch: https://github.com/rsocket/rsocket-kotlin/tree/eap-1.7.20-Beta (just flip flag in gradle.properties) - to see error run tests `gradle rsocket-transport-ktor:rsocket-transport-ktor-tcp:jvmTest`
Workaround is to create class with atomic property which will be created on object init: https://github.com/rsocket/rsocket-kotlin/commit/f3d576921e5b37ce71ec24d713a9b85521f85f18#diff-71a85020213b2120996404a26285b30a8a66ace9b4376b40e61a3a215c061e6e

**Comment by mvicsokolova** [comment]
This bug in the compiler plugin was fixed and will be supported in the next release of `kotlinx-atomicfu`, when Kotlin 1.7.20 is out.
