### ISSUE TITLE
atomicfu 0.21.0 breaks serialization

### ISSUE THREAD

**Issue by recursive-rat4** [Kotlin/kotlinx-atomicfu#317]
Works:
kotlin 1.8.10
atomicfu 0.20.2
serialization 1.5.1

Doesn't work:
kotlin 1.8.10 / 1.8.22 (latest)
atomicfu 0.21.0 (latest)
serialization 1.5.1 (latest)

Any code that uses atomicfu is not yet reached. A serializer generated by the kotlin serialization plugin throws an exception:
```
java.lang.ExceptionInInitializerError
        at n.b.Main.main(Main.kt:74)
Caused by: java.lang.NullPointerException: Cannot load from object array because "<local32>" is null
        at n.b.Config$$serializer.deserialize(Config.kt:19)
        at n.b.Config$$serializer.deserialize(Config.kt:19)
        at n.b.serialization.config.ConfigFormat.decodeFromFile(ConfigFormat.kt:24)
        at n.b.serialization.config.ConfigFormat.decodeFromFile$default(ConfigFormat.kt:22)
        at n.b.Config.<clinit>(Config.kt:52)
        ... 1 more
```
The code at `Config.kt:19` is just `@Serializable`.

**Comment by recursive-rat4** [comment]
Update to Kotlin 1.9.0 solved this.
