### ISSUE TITLE
Unsupported type of atomic receiver expression: GET_VAR

### ISSUE THREAD

**Issue by antailyaqwer** [Kotlin/kotlinx-atomicfu#346]
I have a problem with simple behavior: the project can't build with such code:
```
import kotlinx.atomicfu.atomic

fun <T> Flow<T>.onFirstEmit(block: suspend (T) -> Unit): Flow<T> {
    val isFirstEmit = atomic(false)
    return onEach { value ->
        if (!isFirstEmit.value) {
            block.invoke(value)
            isFirstEmit.value = true
        }
    }
}
```

Stacktrace:
```
e: java.lang.IllegalStateException: Unsupported type of atomic receiver expression: GET_VAR 'val isFirstEmit: kotlinx.atomicfu.AtomicBoolean [val] declared in package.onFirstEmit' type=kotlinx.atomicfu.AtomicBoolean origin=null
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$AtomicfuTransformer.getAtomicFieldInfo(AtomicfuJvmIrTransformer.kt:711)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$AtomicfuTransformer.visitCall(AtomicfuJvmIrTransformer.kt:500)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$AtomicfuTransformer.visitCall(AtomicfuJvmIrTransformer.kt:483)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$AtomicfuTransformer.visitCall(AtomicfuJvmIrTransformer.kt:489)
	at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$AtomicfuTransformer.visitCall(AtomicfuJvmIrTransformer.kt:483)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:26)
```

Env:
atomicfu: 0.22.0
kotlin: 1.9.10 (same problem on 1.8.21 too)
targets: jvm, js (IR), iosX64, iosArm64
coroutines: 1.7.3

**Comment by mvicsokolova** [comment]
Thank you for the report, I've reproduced an issue. I'll try to provide a WA for it.

**Comment by mvicsokolova** [comment]
In the compiler plugin that is enabled in `0.23.0` release, this usage causes the compiler error as well and for now it's expected. You can only declare atomics as properties, they can not be declared as local variables.

For your example, isFirstEmit value should be declared as a property, outside the function:

```
private val isFirstEmit = atomic(false)

fun <T> Flow<T>.onFirstEmit(block: suspend (T) -> Unit): Flow<T> {
    return onEach { value ->
        if (!isFirstEmit.value) {
            block.invoke(value)
            isFirstEmit.value = true
        }
    }
}
```

**Comment by mvicsokolova** [comment]
The compilation with the current version of the compiler plugin will fail with the following error, describing all the constraints:

```
e: java.lang.IllegalStateException: Could not define the type of receiver of the function call CALL 'public final fun <get-value> (): kotlin.Boolean declared in kotlinx.atomicfu.AtomicBoolean' type=kotlin.Boolean origin=GET_PROPERTY: found function call receiver GET_VAR 'val isFirstEmit: kotlinx.atomicfu.AtomicBoolean [val] declared in <root>.onFirstEmit' type=kotlinx.atomicfu.AtomicBoolean origin=null, parentFunction = FUN name:onFirstEmit visibility:public modality:FINAL <> (block:kotlin.Function1<kotlin.Int, kotlin.Unit>) returnType:kotlin.Unit.
Please make sure that you follow these constraints for using atomic properties:
   * To ensure that atomic properties are not accessed out of the current Kotlin module, it is necessary to declare atomic properties as private or internal.
     Alternatively, you can make the containing class private or internal.
     If you need to expose the atomic property value to the public, consider using a delegated property declared within the same scope:
       ```
       private val _a = atomic<T>(initial) 
       public var a: T by _a 
       ```
   * Directly invoke operations on atomic properties, like this:
       ```
       val top = atomic<Node?>(null)
       top.compareAndSet(null, Node(1)) // OK
       ```
   * Refrain from invoking atomic operations on local variables:
       ```
       val top = atomic<Node?>(null)
       val tmp = top
       tmp.compareAndSet(null, Node(1)) // DON'T DO THIS
       ```
   * Avoid leaking references to atomic values in other ways, such as returning them or passing them as parameters.
   * Be cautious with the complexity of data flow within parameters of atomic operations.
     For instance, instead of using intricate expression directly as an argument, e.g.:
       ```
       top.compareAndSet(cur, <complex_expression>)
       ```
     create a separate variable to hold the complex expression's value and then perform the operation:
       ```
       val newValue = <complex_expression>
       top.compareAndSet(cur, newValue) 
       ```
```

**Comment by tamimattafi** [comment]
@mvicsokolova Hi! What if you need new atomic instance for every `onFirstEmit` call? Having a global instance outside the method will use the same value for all callers, which doesn't seem like the needed behavior
