### ISSUE TITLE
atomicfu can't transform classes targeting Java 21

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-atomicfu#389]
Kotlin [allows](https://kotlinlang.org/docs/faq.html#which-versions-of-jvm-does-kotlin-target) targeting Java 21, but atomicfu can't transform corresponding classes:
```
* What went wrong:
Execution failed for task ':transformMainAtomicfu'.
> Unsupported class file major version 65
...
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFileForFields(AtomicFUTransformer.kt:234)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFilesForFields(AtomicFUTransformer.kt:227)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:196)
        at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:521)
```

ASM should be updated to, at least, 9.5: https://asm.ow2.io/versions.html

**Comment by fzhinkin** [comment]
It's only the case if JVM IR transformation is disabled.
