### ISSUE TITLE
Add Gradle project isolation feature support

### ISSUE THREAD

**Issue by dkrasnoff** [Kotlin/kotlinx-atomicfu#459]
Enabled https://docs.gradle.org/current/userguide/isolated_projects.html

**Comment by bitspittle** [comment]
I am using kotlinx-atomicfu in my project , and I just ran Gradle isolated projects diagnostics.

At this point, I fixed everything on my side, with the only remaining issue pointing at [this line](https://github.com/Kotlin/kotlinx-atomicfu/blob/fc175fc575419ca9eae0d3c14cefe9c5cd7ca351/atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt#L181) in your plugin:

```
internal fun Project.getBooleanProperty(name: String) =
    rootProject.findProperty(name)?.toString()?.toBooleanStrict() ?: false
```

Gradle diagnostics callback:
```
kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.getBooleanProperty(AtomicFUGradlePlugin.kt:182)`
org.gradle.api.InvalidUserCodeException: Project ':kotter' cannot access 'Project.findProperty' functionality on another project ':'
	at org.gradle.internal.cc.impl.ProblemReportingCrossProjectModelAccess$ProblemReportingProject.findProperty(ProblemReportingCrossProjectModelAccess.kt:185)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.getBooleanProperty(AtomicFUGradlePlugin.kt:182)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.needsJsIrTransformation(AtomicFUGradlePlugin.kt:191)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$addJsCompilerPluginRuntimeDependency$1.invoke(AtomicFUGradlePlugin.kt:216)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$addJsCompilerPluginRuntimeDependency$1.invoke(AtomicFUGradlePlugin.kt:215)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$withKotlinTargets$1$1.invoke(AtomicFUGradlePlugin.kt:305)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$withKotlinTargets$1$1.invoke(AtomicFUGradlePlugin.kt:305)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.withKotlinTargets$lambda$11$lambda$10(AtomicFUGradlePlugin.kt:305)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:189)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.withKotlinTargets(AtomicFUGradlePlugin.kt:305)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.addJsCompilerPluginRuntimeDependency(AtomicFUGradlePlugin.kt:215)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.access$addJsCompilerPluginRuntimeDependency(AtomicFUGradlePlugin.kt:1)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$configureDependencies$3.invoke(AtomicFUGradlePlugin.kt:111)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$configureDependencies$3.invoke(AtomicFUGradlePlugin.kt:110)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$withPluginWhenEvaluatedDependencies$1.invoke(AtomicFUGradlePlugin.kt:297)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$withPluginWhenEvaluatedDependencies$1.invoke(AtomicFUGradlePlugin.kt:296)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt$whenEvaluated$1.invoke(AtomicFUGradlePlugin.kt:287)
```

I'm not familiar with the details of this project, but you may just be able to [swap out project.findProperty with providers.gradleProperty](https://docs.gradle.org/current/userguide/build_environment.html#accessing_a_project_property):

```kotlin
internal fun Project.getBooleanProperty(name: String): Boolean =
    providers.gradleProperty(name).orNull?.toBooleanStrict() ?: false
```

---

If you want to repro locally:

* `git clone https://github.com/varabyte/kotter`
* `cd kotter`
* `git checkout 093b0ca`
* `./gradlew help --isolated-projects -Dorg.gradle.isolated-projects.diagnostics=true`
