### ISSUE TITLE
jvmTarget 23 is unsupported

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/kotlinx-atomicfu#495]
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:200)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:288)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFileForFields(AtomicFUTransformer.kt:234)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFilesForFields(AtomicFUTransformer.kt:227)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:196)
        at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:527)
```

**Comment by ZacSweers** [comment]
This is in 0.25.0 :/

**Comment by JakeWharton** [comment]
0.26.0 is what actually added support.

**Comment by fzhinkin** [comment]
That's weird :|
I double checked it on my reproducer and the issue is indeed reproducible with `0.25.0`, but everything works fine with `0.26.0`.

**Comment by ZacSweers** [comment]
Working in 0.26!
